version: 0.0
os: linux

files:
  - source: /
    destination: /opt/tomcat/apache-tomcat-9.0.56/webapps/
    
hooks:
  AfterInstall:
    - location: server_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: server_stop.sh
      timeout: 300
      runas: root 
